FROM docker.io/debian:bullseye-slim

WORKDIR /
RUN apt -y update
RUN apt -y install zip wget xz-utils
RUN wget -qO- --no-check-certificate @PI4_FACTORY_BASE_IMAGE@ | xzcat | dd of=/prefs.img skip=@PI4_FACTORY_BASE_IMAGE_PRE_FS_POSITION@ count=@PI4_FACTORY_BASE_IMAGE_PRE_FS_SIZE@
