FROM docker.io/debian:bullseye-slim
RUN apt -y update
RUN apt -y install zip fuse2fs wget mc
RUN mkdir -p /package

RUN mkdir /mnt/rootfs

WORKDIR /

RUN wget -qO- --no-check-certificate @PI4_FACTORY_BASE_IMAGE@ | \
    xzcat | \
    dd of=/rootfs.img skip=@PI4_FACTORY_BASE_IMAGE_ROOT_FS_POSITION@ count=@PI4_FACTORY_BASE_IMAGE_ROOT_FS_SIZE@
