FROM ubuntu:16.04

ENV LANG en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
    apt-get install -y git locales && \
    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8 && \
    apt-get update -y && \
    apt-get install -y git cmake build-essential wget cpio python unzip bc doxygen curl libcurl4-openssl-dev bash ncurses-dev nano zlib1g-dev && \
    git clone https://github.com/nonlinear-labs-dev/nonlinux.git && \
    cd ./nonlinux && \
    git fetch origin && \
    git checkout -f nonlinear_2021.47 && \
    git pull origin nonlinear_2021.47 && \
    sed -i 's/BR2_PACKAGE_C15/# BR2_PACKAGE_C15/g' configs/nonlinear_defconfig && \
    sed -i 's/BR2_PACKAGE_ESPI_DRIVER/# BR2_PACKAGE_ESPI_DRIVER/g' configs/nonlinear_defconfig && \
    sed -i 's/BR2_PACKAGE_PLAYCONTROLLER_DRIVER/# BR2_PACKAGE_PLAYCONTROLLER_DRIVER/g' configs/nonlinear_defconfig && \
    make nonlinear_defconfig && \
    make && \
    cd output/build && \
    find . -type f ! -name '.*' -delete && \
    rm -rf /nonlinux/dl && \
    rm -rf /nonlinux/output/build* && \
    apt-get remove -y git cmake build-essential wget cpio python unzip bc doxygen curl libcurl4-openssl-dev ncurses-dev nano zlib1g-dev

