FROM ubuntu:20.04

ENV LANG en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
    apt-get install -y git gcc-arm-none-eabi cmake build-essential pkg-config

ENV CMAKE_GENERATOR="Unix Makefiles"