FROM ubuntu:20.04

ENV LANG en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

ENV JUST_A_CHANGE=1
RUN apt-get update -y
RUN apt-get install -y git gcc-arm-none-eabi cmake build-essential crossbuild-essential-armhf crossbuild-essential-armel pkg-config

ENV CMAKE_GENERATOR="Unix Makefiles"