FROM docker.io/archlinux:base-@ARCH_VERSION@

RUN pacman-key --init
RUN pacman --noconfirm -Sy
RUN pacman --noconfirm -S archlinux-keyring
RUN pacman-key --populate
RUN sed -i 's/^SigLevel.*/SigLevel = Optional TrustAll/g' /etc/pacman.conf
RUN echo "RemoteFileSigLevel = Optional TrustAll" >> /etc/pacman.conf
RUN echo "[realtime]" >> /etc/pacman.conf
RUN echo "Server = https://pkgbuild.com/~dvzrv/repos/realtime/x86_64/" >> /etc/pacman.conf
RUN echo "Server=https://archive.archlinux.org/repos/@ARCH_VERSION_YEAR@/@ARCH_VERSION_MONTH@/@ARCH_VERSION_DAY@/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist
RUN pacman --noconfirm -Syu
RUN pacman --noconfirm -S rsync arch-install-scripts fuse2fs e2fsprogs wget nano vi

RUN mkdir -p /packages
RUN mkdir -p /tmp/blankdb
WORKDIR /packages
RUN pacman --noconfirm -Syw --cachedir . --dbpath /tmp/blankdb @PACKAGES@

# downgrade wpa_supplicant
RUN rm /packages/wpa_supplicant*
RUN wget https://archive.archlinux.org/packages/w/wpa_supplicant/wpa_supplicant-2%3A2.9-8-x86_64.pkg.tar.zst
RUN wget https://archive.archlinux.org/packages/w/wpa_supplicant/wpa_supplicant-2%3A2.9-8-x86_64.pkg.tar.zst.sig
RUN pacman --noconfirm -Uw --cachedir . --dbpath /tmp/blankdb /packages/wpa_supplicant-2:2.9-8-x86_64.pkg.tar.zst

# setup package database
RUN mkdir -p /nl
RUN repo-add -q /nl/nl.db.tar.gz /packages/*.pkg.tar.zst /packages/*.pkg.tar.xz
RUN rsync -av --progress /packages/* /nl/ --exclude node_modules
RUN echo "[nl]" > /etc/pacman.conf
RUN echo "Server = file:///nl/" >> /etc/pacman.conf
RUN echo "SigLevel = Optional TrustAll" >> /etc/pacman.conf
