FROM docker.io/jurajama/guestfish

WORKDIR /
RUN yum -y install wget
RUN wget -qO- --no-check-certificate @PI4_FACTORY_BASE_IMAGE@ | xzcat | dd of=/bootfs.img skip=@PI4_FACTORY_BASE_IMAGE_ROOT_FS_POSITION@ count=@PI4_FACTORY_BASE_IMAGE_BOOT_FS_SIZE@