FROM docker.io/archlinux:base-20220925.0.89186

RUN pacman-key --init && \
    pacman --noconfirm -Sy && \
    pacman --noconfirm -S archlinux-keyring && \
    pacman-key --populate && \
    pacman --noconfirm -Syu && \
    pacman --noconfirm -S git fakeroot binutils sudo make gcc diffutils bash arch-install-scripts && \
    useradd bob -m && \
    passwd -d bob && \
    printf 'bob ALL=(ALL) ALL\n' | tee -a /etc/sudoers && \
    cd /tmp && \
    sudo -u bob git clone https://aur.archlinux.org/yay-git.git && \
    cd /tmp/yay-git && \
    sudo -u bob makepkg -si --noconfirm && \
    sudo -u bob yay --noconfirm -Syu && \
    sudo -u bob yay --noconfirm -S debtap && \
    pacman --noconfirm -R yay-git git make gcc

RUN debtap -u
RUN pacman --noconfirm -S wget
RUN wget http://h2949050.stratoserver.net/build-tools2/xz-5.2.5-linux-x86_64.tar.gz -O /xz-5.2.5-linux-x86_64.tar.gz
