FROM docker.io/archlinux:base-20220501.0.54834

RUN pacman-key --init && \
    pacman --noconfirm -Sy && \
    pacman --noconfirm -S archlinux-keyring && \
    pacman-key --populate && \
    pacman --noconfirm -Syyuu && \
    pacman --noconfirm -S cmake gcc ninja pkg-config glibmm libsoup boost libpng freetype2 alsa-lib libpng flac util-linux-libs png++ && \
    pacman --noconfirm -Syyuu && pacman --noconfirm -S ccache make

ENV CMAKE_GENERATOR="Ninja"
