FROM docker.io/archlinux:base-20220501.0.54834

RUN pacman-key --init
RUN pacman --noconfirm -Sy
RUN pacman --noconfirm -S archlinux-keyring
RUN pacman-key --populate

RUN pacman --noconfirm -Syyuu && pacman --noconfirm -S cmake gcc make pkg-config glibmm libsoup boost libpng freetype2 alsa-lib libpng flac util-linux-libs png++
RUN pacman --noconfirm -Syyuu && pacman --noconfirm -S ninja
