FROM docker.io/archlinux:base-20220501.0.54834

RUN pacman-key --init
RUN pacman --noconfirm -Sy
RUN pacman --noconfirm -S archlinux-keyring
RUN pacman-key --populate

RUN pacman --noconfirm -Syyuu && pacman --noconfirm -S nodejs npm jre17-openjdk-headless
RUN npm install -g meteor jquery @types/meteor meteor-build-client@0.4.1 typescript
RUN meteor add kadira:flow-router blaze-html-templates jquery kadira:blaze-layout autoupdate typescript reactive-var meteortesting:mocha less smallhacks:jquery-contextmenu
RUN wget https://github.com/gwtproject/gwt/releases/download/2.10.0/gwt-2.10.0.zip | unzip