FROM docker.io/node:14.21.1-bullseye-slim

ENV PATH="${PATH}:/root/.meteor"

RUN apt-get -y update && \
    apt-get -y install wget nodejs npm openjdk-17-jdk-headless sudo unzip cmake ninja-build make pkg-config gcc g++ && \
    wget https://github.com/gwtproject/gwt/releases/download/2.10.0/gwt-2.10.0.zip && \
    unzip gwt-2.10.0.zip && \
    npm install -g --unsafe-perm meteor jquery @types/meteor meteor-build-client@0.4.1 typescript && \
    meteor --allow-superuser create --minimal app && \
    cd /app && \
    meteor --allow-superuser add kadira:flow-router blaze-html-templates jquery kadira:blaze-layout autoupdate typescript reactive-var meteortesting:mocha less smallhacks:jquery-contextmenu

ENV CMAKE_GENERATOR="Ninja"
ENV METEOR_ALLOW_SUPERUSER=1
