FROM docker.io/alpine:3.16.2

WORKDIR /root
COPY ./package.json .

RUN apk add --no-cache nodejs npm g++ bash && \
    npm install -g ts-node typescript@4.7.4 && \
    npm install && \
    node -v && \
    npm -v && \
    tsc -v
