FROM docker.io/alpine:3.16.2

RUN apk add --no-cache nodejs npm g++ bash
RUN npm install -g ts-node typescript@4.7.4

WORKDIR /root
COPY ./package.json .

RUN npm install 

RUN node -v
RUN npm -v
RUN tsc -v
