if(CROSS_BUILD)
    target_include_directories(${PROJECT_NAME} PRIVATE /staging/usr/include)
    target_link_libraries(${PROJECT_NAME} PRIVATE nltools)
else()
    target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_SOURCE_DIR}/packages/nltools/include)
    target_link_libraries(${PROJECT_NAME} PRIVATE nltools)
    add_dependencies(${PROJECT_NAME} nltools)
endif()