if(CROSS_BUILD)
    cmake_minimum_required(VERSION 3.02)
    target_include_directories(${PROJECT_NAME} PRIVATE /staging/usr/include/)
    target_link_libraries(${PROJECT_NAME} PRIVATE /staging/usr/lib/libnltools.so)
else()
    target_include_directories(${PROJECT_NAME} PUBLIC $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/package>)
    target_link_libraries(${PROJECT_NAME} PRIVATE nltools)
    add_dependencies(${PROJECT_NAME} nltools)
endif()