

function(deb DEPENDENCIES DESCRIPTION)
    SET(CPACK_GENERATOR "DEB")
    SET(CPACK_BINARY_DEB On)
    SET(CPACK_PACKAGE_CONTACT "info@nonlinear-labs.de")
    SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Nonlinear Labs GmbH")
    SET(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
    SET(CPACK_DEBIAN_PACKAGE_DEPENDS ${DEPENDENCIES})
    SET(CPACK_DEBIAN_PACKAGE_DESCRIPTION ${DESCRIPTION})
    SET(CPACK_CMAKE_GENERATOR Ninja) # this is to prevent complete rebuild in preinstall step    
    INCLUDE(CPack)
endfunction()